name: chat-app
region: us-east-1
yamlVersion: 2

services:
  databases:
   - name: chat-app
     type: mongo-atlas
     region: us-east-1

backend:
    path: express
    language:
        name: js
    scripts:
      deploy: npm install
    functions:
        - name: express
          path: .
          entry: app.mjs
          type: httpServer

frontend:
  path: client
  sdk:
    language: ts
  publish: dist
  environment:
    VITE_API_URL: ${{ backend.functions.express.url }}
  scripts:
    deploy:
      - npm install
    build:
      - npm run build
    start:
      - npm install
      - npm run dev
