name: chat-app
region: eu-central-1
yamlVersion: 2
services:
    databases:
        - name: chat-app
          region: eu-central-1
          type: mongo-atlas

backend:
    functions:
        - entry: dist/app.js
          handler: handler
          name: express
          path: .
          type: aws
    language:
        name: js
    path: express
    scripts:
        local:
            - npm install
            - npm run build
        deploy:
            - npm install
            - npm run build

frontend:
    environment:
        VITE_API_URL: ${{ backend.functions.express.url }}
    path: client
    publish: dist
    scripts:
        build:
            - npm run build
        deploy:
            - npm install
        start:
            - npm install
            - npm run dev
    sdk:
        language: ts
